[project]
name = "ai-chat-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.45.1",
    "torch>=2.7.1",
    "transformers>=4.52.4",
]
